
POST http://localhost:6000/api/travels HTTP/1.1
content-type: application/json
X-Auth-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJ1c2VyMTNza2tsd2V2NHAydHJhdmVsIiwicm9sZSI6Ik9XTkVSIiwiaWF0IjoxNjE0OTU3NDIzLCJleHAiOjE2MTQ5NTc1NDN9.n88PNEHjRtLgVSzOwbQIlAsz_TG-1NpHZ-5KGGb4XCE

{
    "location": "North Germany",
    "purpose": "Horllyday",
    "image_url": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FMunich&psig=AOvVaw34DQjAh_NZRcBUNhF9D0Wz&ust=1614257356342000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCJD3vrnHgu8CFQAAAAAdAAAAABAD",
    "description": "I Traveled to muchen on a horllyday trip it was an amazing experience",
    "year": "2015-09-07"
}



###
GET http://localhost:3000/api/travels/ HTTP/1.1
Content-Type: application/application/json
X-Auth-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJ1c2VyMWdteXFnN28xa2xsZzB4cnF0cmF2ZWwiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE2MTQzODI5MzksImV4cCI6MTYxNDM4NjUzOX0.IkgrYZRphkWc_242P7qqjD4EdpeMhl9rp0Zog5cWQbg


###
GET http://localhost:3000/api/travels/travel1gmyqg97kkllgsxaquser HTTP/1.1
Content-Type: application/application/json
X-Auth-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJ1c2VyMWdteXFnN28xa2xsZzB4cnF0cmF2ZWwiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE2MTQzODI5MzksImV4cCI6MTYxNDM4NjUzOX0.IkgrYZRphkWc_242P7qqjD4EdpeMhl9rp0Zog5cWQbg




